name: quill_native_bridge_macos
description: "macOS implementation of the quill_native_bridge plugin."
version: 0.0.1-dev.4
homepage: https://github.com/FlutterQuill/quill-native-bridge/tree/main/quill_native_bridge_macos
repository: https://github.com/FlutterQuill/quill-native-bridge/tree/main/quill_native_bridge_macos
issue_tracker: https://github.com/FlutterQuill/quill-native-bridge/issues?q=is%3Aissue+is%3Aopen+label%3A%22platform-macos%22
documentation: https://github.com/FlutterQuill/quill-native-bridge/tree/main/quill_native_bridge_macos

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: '>=3.0.0'

dependencies:
  flutter:
    sdk: flutter
  quill_native_bridge_platform_interface: ^0.0.1-dev.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  pigeon: ^22.6.2

flutter:
  plugin:
    implements: quill_native_bridge
    platforms:
      macos:
        pluginClass: QuillNativeBridgePlugin
        dartPluginClass: QuillNativeBridgeMacOS
