name: ğŸ§ª Run Tests

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  tests:
    name: Check lints and tests
    runs-on: ubuntu-latest

    steps:
      - name: ğŸ“¦ Checkout repository
        uses: actions/checkout@v4

      - name: ğŸ› ï¸ Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
          cache: true

      - name: ğŸ” Verify Flutter installation
        run: flutter --version

      # TODO: Might use https://pub.dev/packages/melos and move the packages (e.g., `quill_native_brdige`) into the 'packages' directory
      
      - name: ğŸ“¦ Install quill_native_bridge dependencies
        run: flutter pub get -C quill_native_bridge

      - name: ğŸ“¦ Install quill_native_bridge_android dependencies
        run: flutter pub get -C quill_native_bridge_android

      - name: ğŸ“¦ Install quill_native_bridge_ios dependencies
        run: flutter pub get -C quill_native_bridge_ios

      - name: ğŸ“¦ Install quill_native_bridge_linux dependencies
        run: flutter pub get -C quill_native_bridge_linux

      - name: ğŸ“¦ Install quill_native_bridge_macos dependencies
        run: flutter pub get -C quill_native_bridge_macos

      - name: ğŸ“¦ Install quill_native_bridge_platform_interface dependencies
        run: flutter pub get -C quill_native_bridge_platform_interface

      - name: ğŸ“¦ Install quill_native_bridge_web dependencies
        run: flutter pub get -C quill_native_bridge_web

      - name: ğŸ“¦ Install quill_native_bridge_windows dependencies
        run: flutter pub get -C quill_native_bridge_windows

      - name: ğŸ“¦ Install the example's dependencies
        run: flutter pub get -C quill_native_bridge/example --enforce-lockfile

      - name: ğŸ” Run Flutter analysis
        run: flutter analyze

      - name: ğŸ§¹ Check Dart code formatting
        run: dart format --set-exit-if-changed .
      
      - name: ğŸ” Preview Dart proposed changes
        run: dart fix --dry-run

      # TODO: Run the check (flutter pub publish --dry-run) for all packages (e.g., quill_native_bridge_platform_interface)

      - name: ğŸ§ª Run Flutter tests
        run: |
          for package in quill_native_bridge quill_native_bridge_platform_interface quill_native_bridge_android quill_native_bridge_ios quill_native_bridge_macos quill_native_bridge_windows quill_native_bridge_linux quill_native_bridge_web; do
            if [ -d "$package/test" ]; then
              (cd "$package" && flutter test)
            else
              echo "No test directory found for $package. Skipping."
            fi
          done

      # From https://docs.flutter.dev/get-started/install/linux/desktop#development-tools
      - name: ğŸ§ Install required Linux packages to run integration tests
        run: sudo apt-get update -y && sudo apt-get upgrade -y && sudo apt-get install -y curl git unzip xz-utils zip libglu1-mesa && sudo apt-get install clang cmake git ninja-build pkg-config libgtk-3-dev liblzma-dev libstdc++-12-dev

      # See https://docs.flutter.dev/get-started/install/linux/desktop#development-tools
      - name: ğŸ§ Checking the package versions compatibility with Flutter
        run: flutter doctor

      # TODO: Move integration tests step into a separate workflow with support for all platforms
      - name: ğŸ§ª Run Flutter integration tests
        run: cd quill_native_bridge/example && flutter test integration_test -d linux
        timeout-minutes: 5

