name: ğŸ§ª Run Tests

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  tests:
    name: Check lints and tests
    runs-on: ubuntu-latest

    steps:
      - name: ğŸ“¦ Checkout repository
        uses: actions/checkout@v4

      - name: ğŸ› ï¸ Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
          cache: true

      - name: ğŸ” Verify Flutter installation
        run: flutter --version

      # TODO: Might use https://pub.dev/packages/melos and move the packages (e.g., `quill_native_brdige`) into the 'packages' directory
      
      - name: ğŸ“¦ Install quill_native_bridge dependencies
        run: flutter pub get -C quill_native_bridge

      - name: ğŸ“¦ Install quill_native_bridge_android dependencies
        run: flutter pub get -C quill_native_bridge_android

      - name: ğŸ“¦ Install quill_native_bridge_ios dependencies
        run: flutter pub get -C quill_native_bridge_ios

      - name: ğŸ“¦ Install quill_native_bridge_linux dependencies
        run: flutter pub get -C quill_native_bridge_linux

      - name: ğŸ“¦ Install quill_native_bridge_macos dependencies
        run: flutter pub get -C quill_native_bridge_macos

      - name: ğŸ“¦ Install quill_native_bridge_platform_interface dependencies
        run: flutter pub get -C quill_native_bridge_platform_interface

      - name: ğŸ“¦ Install quill_native_bridge_web dependencies
        run: flutter pub get -C quill_native_bridge_web

      - name: ğŸ“¦ Install quill_native_bridge_windows dependencies
        run: flutter pub get -C quill_native_bridge_windows

      - name: ğŸ“¦ Install the example's dependencies
        run: flutter pub get -C quill_native_bridge/example --enforce-lockfile

      - name: ğŸ” Run Flutter analysis
        run: flutter analyze

      - name: ğŸ§¹ Check Dart code formatting
        run: dart format --set-exit-if-changed .
      
      - name: ğŸ” Preview Dart proposed changes
        run: dart fix --dry-run

      - name: ğŸ“¦ Check if packages are ready for publishing
        run: |
          flutter pub publish --dry-run -C quill_native_bridge
          flutter pub publish --dry-run -C quill_native_bridge_platform_interface
          flutter pub publish --dry-run -C quill_native_bridge_android
          flutter pub publish --dry-run -C quill_native_bridge_ios
          flutter pub publish --dry-run -C quill_native_bridge_macos
          flutter pub publish --dry-run -C quill_native_bridge_linux
          flutter pub publish --dry-run -C quill_native_bridge_windows
          flutter pub publish --dry-run -C quill_native_bridge_web

      - name: ğŸ§ª Run Flutter tests
        run: flutter test

      # TODO: Move integration tests step into a separate workflow with support for all platforms
      - name: ğŸ§ª Run Flutter integration tests
        run: flutter test integration_test -d linux -C quill_native_bridge/example

