name: ğŸ§ª Run Tests

on:
  pull_request:
    branches: [main]

jobs:    
  desktop-tests:
    name: ğŸ–¥ï¸ Desktop Tests (${{ matrix.os }} Latest)
    strategy:
      # This prevents one failure from stopping the entire run.
      fail-fast: false
      # TODO: Restore windows, run Android and iOS unit tests, cache swift-format
      matrix:
        os: [ubuntu, macos]
    runs-on: ${{ matrix.os }}-latest
    timeout-minutes: 30

    steps:
      - name: ğŸ“¥ Checkout Repository
        uses: actions/checkout@v4

      - name: ğŸ› ï¸ Setup Flutter (Stable)
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
          cache: true
      
      - name: ğŸ“¦ Install all package dependencies
        run: dart ./scripts/pub_get.dart

      - name: ğŸ“¦ Install example dependencies
        run: flutter pub get -C quill_native_bridge/example

      - name: ğŸ§© Run Flutter unit tests
        run: dart ./scripts/test.dart
        timeout-minutes: 5

      - name: ğŸ“¦ Install Linux dependencies
        if: runner.os == 'Linux'
        run: |
          sudo apt-get update -y
          sudo apt-get install -y curl git unzip xz-utils zip libglu1-mesa
          sudo apt-get install -y clang cmake ninja-build pkg-config libgtk-3-dev liblzma-dev libstdc++-12-dev

      # For more details: https://docs.flutter.dev/testing/integration-tests#test-on-a-desktop-platform

      - name: ğŸ§ª Run Flutter integration tests on Linux
        if: runner.os == 'Linux'
        uses: smithki/xvfb-action@v1.1.2
        with:
          run: flutter test integration_test -d linux -r github
          working-directory: quill_native_bridge/example

      - name: ğŸ§ª Run Flutter integration tests on Non-Linux platforms
        if: runner.os != 'Linux'
        run: flutter test integration_test -d ${{ runner.os }}
        working-directory: quill_native_bridge/example
